FROM docker.io/library/elixir:1.18-slim AS base

ENV MIX_ENV=prod

RUN apt-get update && \
	apt-get install -y --no-install-recommends \
	ca-certificates \
	clang \
	cmake \
	git \
	make \
	&& rm -rf /var/lib/apt/lists/*
RUN mkdir /app
WORKDIR /app
RUN mix local.hex --force
RUN mix local.rebar --force

FROM base AS deps
COPY mix.exs .
COPY mix.lock .
RUN mix deps.get --only $MIX_ENV
RUN mkdir config
COPY config/config.exs config/${MIX_ENV}.exs config/
RUN mix deps.compile

FROM deps AS app
COPY priv ./priv
COPY assets ./assets
COPY lib ./lib
RUN mix assets.deploy
RUN mix ua_inspector.download
RUN mix ref_inspector.download
RUN mix compile
COPY config/runtime.exs config/
RUN mix release

FROM docker.io/library/debian:12-slim AS release
ENV LANG=C.UTF-8
RUN apt-get update && \
	apt-get install -y --no-install-recommends \
	openssl \
	&& rm -rf /var/lib/apt/lists/*
COPY --from=app /app/_build/prod/rel .
ENTRYPOINT [ "/scouter/bin/scouter" ]
CMD [ "start" ]

