FROM docker.io/library/elixir:1.18-alpine AS base

ENV MIX_ENV=prod

RUN apk add git make gcc pkgconfig glib-dev musl-dev
RUN mkdir /app
WORKDIR /app
RUN mix local.hex --force
RUN mix local.rebar --force

FROM base AS deps
COPY mix.exs .
COPY mix.lock .
RUN mix deps.get --only $MIX_ENV
RUN mkdir config
COPY config/config.exs config/${MIX_ENV}.exs config/
RUN mix deps.compile

FROM deps AS app
COPY priv ./priv
COPY assets ./assets
COPY lib ./lib
RUN mix assets.deploy

RUN mix compile
COPY config/runtime.exs config/
RUN mix release

FROM docker.io/library/alpine:3.18 AS release
COPY --from=app /app/_build/prod/rel .
RUN apk add --no-cache ncurses-libs libstdc++ openssl
ENTRYPOINT [ "/analytics/bin/analytics" ]
CMD [ "start" ]

